// Code generated by "stringer -type=jobType"; DO NOT EDIT.

package job

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[first-0]
	_ = x[SuccessfulJobType-1]
	_ = x[last-2]
}

const _jobType_name = "firstExampleJobTypelast"

var _jobType_index = [...]uint8{0, 5, 19, 23}

func (i jobType) String() string {
	if i < 0 || i >= jobType(len(_jobType_index)-1) {
		return "jobType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _jobType_name[_jobType_index[i]:_jobType_index[i+1]]
}
